## 🚗 Automobile Accident Severity Prediction

Given *data about accidents in the US*, let's try to predict the **severity** of a given accident.

We will use a TensorFlow ANN to make our predictions.

Data source: https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow as tf

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('archive/US_Accidents_March23.csv', nrows=100000)

In [3]:
data

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,Right lane blocked due to accident on I-70 Eas...,I-70 E,Dayton,Montgomery,OH,45424,US,US/Eastern,KFFO,2016-02-08 05:58:00,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,Reynoldsburg,Franklin,OH,43068-3402,US,US/Eastern,KCMH,2016-02-08 05:51:00,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,Williamsburg,Clermont,OH,45176,US,US/Eastern,KI69,2016-02-08 06:56:00,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,Dayton,Montgomery,OH,45417,US,US/Eastern,KDAY,2016-02-08 07:38:00,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,Dayton,Montgomery,OH,45459,US,US/Eastern,KMGY,2016-02-08 07:53:00,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,A-100002,Source2,3,2016-04-05 15:52:14,2016-04-05 16:52:14,32.731979,-117.111244,NaN,NaN,0.00,Right hand shoulder blocked due to accident on...,CA-15 N,San Diego,San Diego,CA,92105,US,US/Pacific,KSAN,2016-04-05 15:51:00,72.0,NaN,46.0,30.01,10.0,NW,8.1,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
99996,A-100003,Source2,3,2016-04-05 15:57:10,2016-04-05 16:57:10,33.913029,-118.125389,NaN,NaN,0.00,Two lanes blocked and queueing traffic due to ...,Bellflower Blvd,Downey,Los Angeles,CA,90242,US,US/Pacific,KLGB,2016-04-05 15:53:00,82.9,NaN,24.0,29.97,10.0,South,6.9,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
99997,A-100004,Source2,2,2016-04-05 16:02:16,2016-04-05 17:02:16,34.121517,-117.536896,NaN,NaN,0.00,Accident on Day Creek Blvd near Baseline Rd.,Baseline Rd,Rancho Cucamonga,San Bernardino,CA,91739,US,US/Pacific,KONT,2016-04-05 15:53:00,91.0,NaN,12.0,29.93,10.0,NW,6.9,NaN,Mostly Cloudy,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
99998,A-100005,Source3,2,2016-04-05 16:01:17,2016-04-05 17:01:17,33.995079,-117.361183,NaN,NaN,0.00,Lane blocked on exit ramp due to accident moto...,Pomona Fwy W,Riverside,Riverside,CA,92501,US,US/Pacific,KRAL,2016-04-05 15:53:00,91.9,NaN,12.0,29.92,10.0,West,8.1,NaN,Mostly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-100006,Source2,2,2016-04-05 16:06:41,2016-04-05 17:06:41,34.034119,-118.013443,NaN,NaN,0.00,Accident on Ankerton St near Coleford Ave.,Ankerton St,Whittier,Los Angeles,CA,90601-1307,US,US/Pacific,KEMT,2016-04-05 15:45:00,89.6,NaN,16.0,29.98,10.0,South,5.8,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     100000 non-null  str
 1   Source                 100000 non-null  str
 2   Severity               100000 non-null  int64
 3   Start_Time             100000 non-null  str
 4   End_Time               100000 non-null  str
 5   Start_Lat              100000 non-null  float64
 6   Start_Lng              100000 non-null  float64
 7   End_Lat                0 non-null       float64
 8   End_Lng                0 non-null       float64
 9   Distance(mi)           100000 non-null  float64
 10  Description            100000 non-null  str
 11  Street                 100000 non-null  str
 12  City                   99999 non-null   str
 13  County                 100000 non-null  str
 14  State                  100000 non-null  str
 15  Zipcode                99993 non-null   str
 16  Country                100000 non-null  str
 17  Timezone               99993 non-null   str
 18  Airport_Code           99993 non-null   str
 19  Weather_Timestamp      98946 non-null   str
 20  Temperature(F)         98409 non-null   float64
 21  Wind_Chill(F)          4322 non-null    float64
 22  Humidity(%)            98144 non-null   float64
 23  Pressure(in)           98708 non-null   float64
 24  Visibility(mi)         98154 non-null   float64
 25  Wind_Direction         98936 non-null   str
 26  Wind_Speed(mph)        76180 non-null   float64
 27  Precipitation(in)      7368 non-null    float64
 28  Weather_Condition      98396 non-null   str
 29  Amenity                100000 non-null  bool
 30  Bump                   100000 non-null  bool
 31  Crossing               100000 non-null  bool
 32  Give_Way               100000 non-null  bool
 33  Junction               100000 non-null  bool
 34  No_Exit                100000 non-null  bool
 35  Railway                100000 non-null  bool
 36  Roundabout             100000 non-null  bool
 37  Station                100000 non-null  bool
 38  Stop                   100000 non-null  bool
 39  Traffic_Calming        100000 non-null  bool
 40  Traffic_Signal         100000 non-null  bool
 41  Turning_Loop           100000 non-null  bool
 42  Sunrise_Sunset         99999 non-null   str
 43  Civil_Twilight         99999 non-null   str
 44  Nautical_Twilight      99999 non-null   str
 45  Astronomical_Twilight  99999 non-null   str
dtypes: bool(13), float64(12), int64(1), str(20)
memory usage: 26.4 MB

### Preprocessing

In [5]:
df = data.copy()

In [6]:
df.isna().mean()

ID                       0.00000
Source                   0.00000
Severity                 0.00000
Start_Time               0.00000
End_Time                 0.00000
Start_Lat                0.00000
Start_Lng                0.00000
End_Lat                  1.00000
End_Lng                  1.00000
Distance(mi)             0.00000
Description              0.00000
Street                   0.00000
City                     0.00001
County                   0.00000
State                    0.00000
Zipcode                  0.00007
Country                  0.00000
Timezone                 0.00007
Airport_Code             0.00007
Weather_Timestamp        0.01054
Temperature(F)           0.01591
Wind_Chill(F)            0.95678
Humidity(%)              0.01856
Pressure(in)             0.01292
Visibility(mi)           0.01846
Wind_Direction           0.01064
Wind_Speed(mph)          0.23820
Precipitation(in)        0.92632
Weather_Condition        0.01604
Amenity                  0.00000
Bump                     0.00000
Crossing                 0.00000
Give_Way                 0.00000
Junction                 0.00000
No_Exit                  0.00000
Railway                  0.00000
Roundabout               0.00000
Station                  0.00000
Stop                     0.00000
Traffic_Calming          0.00000
Traffic_Signal           0.00000
Turning_Loop             0.00000
Sunrise_Sunset           0.00001
Civil_Twilight           0.00001
Nautical_Twilight        0.00001
Astronomical_Twilight    0.00001
dtype: float64

In [7]:
null_columns = ['End_Lat', 'End_Lng', 'Precipitation(in)', 'Wind_Chill(F)']

df = df.drop(null_columns, axis=1)

In [8]:
df.isna().sum()

ID                           0
Source                       0
Severity                     0
Start_Time                   0
End_Time                     0
Start_Lat                    0
Start_Lng                    0
Distance(mi)                 0
Description                  0
Street                       0
City                         1
County                       0
State                        0
Zipcode                      7
Country                      0
Timezone                     7
Airport_Code                 7
Weather_Timestamp         1054
Temperature(F)            1591
Humidity(%)               1856
Pressure(in)              1292
Visibility(mi)            1846
Wind_Direction            1064
Wind_Speed(mph)          23820
Weather_Condition         1604
Amenity                      0
Bump                         0
Crossing                     0
Give_Way                     0
Junction                     0
No_Exit                      0
Railway                      0
Roundabout                   0
Station                      0
Stop                         0
Traffic_Calming              0
Traffic_Signal               0
Turning_Loop                 0
Sunrise_Sunset               1
Civil_Twilight               1
Nautical_Twilight            1
Astronomical_Twilight        1
dtype: int64

In [9]:
df = df.dropna(axis=0).reset_index(drop=True)

In [10]:
print("Total missing values:", df.isna().sum().sum())

Total missing values: 0

In [11]:
df

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,Williamsburg,Clermont,OH,45176,US,US/Eastern,KI69,2016-02-08 06:56:00,36.0,100.0,29.67,10.0,SW,3.5,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day
1,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,Dayton,Montgomery,OH,45417,US,US/Eastern,KDAY,2016-02-08 07:38:00,35.1,96.0,29.64,9.0,SW,4.6,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day
2,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,Dayton,Montgomery,OH,45459,US,US/Eastern,KMGY,2016-02-08 07:53:00,36.0,89.0,29.65,6.0,SW,3.5,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
3,A-6,Source2,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,0.01,Accident on I-270 Outerbelt Northbound near Ex...,Westerville Rd,Westerville,Franklin,OH,43081,US,US/Eastern,KCMH,2016-02-08 07:51:00,37.9,97.0,29.63,7.0,SSW,3.5,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
4,A-7,Source2,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,0.00,Accident on Oakridge Dr at Woodward Ave. Expec...,N Woodward Ave,Dayton,Montgomery,OH,45417-2476,US,US/Eastern,KDAY,2016-02-08 07:56:00,34.0,100.0,29.66,7.0,WSW,3.5,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74914,A-100002,Source2,3,2016-04-05 15:52:14,2016-04-05 16:52:14,32.731979,-117.111244,0.00,Right hand shoulder blocked due to accident on...,CA-15 N,San Diego,San Diego,CA,92105,US,US/Pacific,KSAN,2016-04-05 15:51:00,72.0,46.0,30.01,10.0,NW,8.1,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
74915,A-100003,Source2,3,2016-04-05 15:57:10,2016-04-05 16:57:10,33.913029,-118.125389,0.00,Two lanes blocked and queueing traffic due to ...,Bellflower Blvd,Downey,Los Angeles,CA,90242,US,US/Pacific,KLGB,2016-04-05 15:53:00,82.9,24.0,29.97,10.0,South,6.9,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
74916,A-100004,Source2,2,2016-04-05 16:02:16,2016-04-05 17:02:16,34.121517,-117.536896,0.00,Accident on Day Creek Blvd near Baseline Rd.,Baseline Rd,Rancho Cucamonga,San Bernardino,CA,91739,US,US/Pacific,KONT,2016-04-05 15:53:00,91.0,12.0,29.93,10.0,NW,6.9,Mostly Cloudy,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
74917,A-100005,Source3,2,2016-04-05 16:01:17,2016-04-05 17:01:17,33.995079,-117.361183,0.00,Lane blocked on exit ramp due to accident moto...,Pomona Fwy W,Riverside,Riverside,CA,92501,US,US/Pacific,KRAL,2016-04-05 15:53:00,91.9,12.0,29.92,10.0,West,8.1,Mostly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
74918,A-100006,Source2,2,2016-04-05 16:06:41,2016-04-05 17:06:41,34.034119,-118.013443,0.00,Accident on Ankerton St near Coleford Ave.,Ankerton St,Whittier,Los Angeles,CA,90601-1307,US,US/Pacific,KEMT,2016-04-05 15:45:00,89.6,16.0,29.98,10.0,South,5.8,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [12]:
# Remove unnecessary columns
{column: len(df[column].unique()) for column in df.columns if df.dtypes[column] == 'str'}

{'ID': 74919,
 'Source': 2,
 'Start_Time': 74116,
 'End_Time': 72791,
 'Description': 55458,
 'Street': 7843,
 'City': 758,
 'County': 70,
 'State': 3,
 'Zipcode': 9634,
 'Country': 1,
 'Timezone': 2,
 'Airport_Code': 118,
 'Weather_Timestamp': 29866,
 'Wind_Direction': 23,
 'Weather_Condition': 41,
 'Sunrise_Sunset': 2,
 'Civil_Twilight': 2,
 'Nautical_Twilight': 2,
 'Astronomical_Twilight': 2}

In [13]:
high_cardinality_columns = ['Zipcode', 'ID', 'Description', 'Street']

df = df.drop(high_cardinality_columns, axis=1)

In [14]:
{column: len(df[column].unique()) for column in df.columns if df.dtypes[column] == 'str'}

{'Source': 2,
 'Start_Time': 74116,
 'End_Time': 72791,
 'City': 758,
 'County': 70,
 'State': 3,
 'Country': 1,
 'Timezone': 2,
 'Airport_Code': 118,
 'Weather_Timestamp': 29866,
 'Wind_Direction': 23,
 'Weather_Condition': 41,
 'Sunrise_Sunset': 2,
 'Civil_Twilight': 2,
 'Nautical_Twilight': 2,
 'Astronomical_Twilight': 2}

In [15]:
# Removing Country with only one value
df = df.drop('Country', axis=1)

In [16]:
df

,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),City,County,State,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,Williamsburg,Clermont,OH,US/Eastern,KI69,2016-02-08 06:56:00,36.0,100.0,29.67,10.0,SW,3.5,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day
1,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,Dayton,Montgomery,OH,US/Eastern,KDAY,2016-02-08 07:38:00,35.1,96.0,29.64,9.0,SW,4.6,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day
2,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Dayton,Montgomery,OH,US/Eastern,KMGY,2016-02-08 07:53:00,36.0,89.0,29.65,6.0,SW,3.5,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
3,Source2,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,0.01,Westerville,Franklin,OH,US/Eastern,KCMH,2016-02-08 07:51:00,37.9,97.0,29.63,7.0,SSW,3.5,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
4,Source2,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,0.00,Dayton,Montgomery,OH,US/Eastern,KDAY,2016-02-08 07:56:00,34.0,100.0,29.66,7.0,WSW,3.5,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74914,Source2,3,2016-04-05 15:52:14,2016-04-05 16:52:14,32.731979,-117.111244,0.00,San Diego,San Diego,CA,US/Pacific,KSAN,2016-04-05 15:51:00,72.0,46.0,30.01,10.0,NW,8.1,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
74915,Source2,3,2016-04-05 15:57:10,2016-04-05 16:57:10,33.913029,-118.125389,0.00,Downey,Los Angeles,CA,US/Pacific,KLGB,2016-04-05 15:53:00,82.9,24.0,29.97,10.0,South,6.9,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
74916,Source2,2,2016-04-05 16:02:16,2016-04-05 17:02:16,34.121517,-117.536896,0.00,Rancho Cucamonga,San Bernardino,CA,US/Pacific,KONT,2016-04-05 15:53:00,91.0,12.0,29.93,10.0,NW,6.9,Mostly Cloudy,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
74917,Source3,2,2016-04-05 16:01:17,2016-04-05 17:01:17,33.995079,-117.361183,0.00,Riverside,Riverside,CA,US/Pacific,KRAL,2016-04-05 15:53:00,91.9,12.0,29.92,10.0,West,8.1,Mostly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
74918,Source2,2,2016-04-05 16:06:41,2016-04-05 17:06:41,34.034119,-118.013443,0.00,Whittier,Los Angeles,CA,US/Pacific,KEMT,2016-04-05 15:45:00,89.6,16.0,29.98,10.0,South,5.8,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [17]:
def get_years(df, column):
    return df[column].apply(lambda x: x[0:4])
    
def get_months(df, column):
    return df[column].apply(lambda x: x[5:7])

In [18]:
df['Start_Time_Year'] = get_years(df, 'Start_Time').astype(int)
df['End_Time_Year'] = get_years(df, 'End_Time').astype(int)
df['Weather_Timestamp_Year'] = get_years(df, 'Weather_Timestamp').astype(int)

df['Start_Time_Month'] = get_months(df, 'Start_Time').astype(int)
df['End_Time_Month'] = get_months(df, 'End_Time').astype(int)
df['Weather_Timestamp_Month'] = get_months(df, 'Weather_Timestamp').astype(int)

df = df.drop(['End_Time', 'Start_Time', 'Weather_Timestamp'], axis=1)

In [19]:
df

,Source,Severity,Start_Lat,Start_Lng,Distance(mi),City,County,State,Timezone,Airport_Code,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Start_Time_Year,End_Time_Year,Weather_Timestamp_Year,Start_Time_Month,End_Time_Month,Weather_Timestamp_Month
0,Source2,2,39.063148,-84.032608,0.01,Williamsburg,Clermont,OH,US/Eastern,KI69,36.0,100.0,29.67,10.0,SW,3.5,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day,2016,2016,2016,2,2,2
1,Source2,3,39.747753,-84.205582,0.01,Dayton,Montgomery,OH,US/Eastern,KDAY,35.1,96.0,29.64,9.0,SW,4.6,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day,2016,2016,2016,2,2,2
2,Source2,2,39.627781,-84.188354,0.01,Dayton,Montgomery,OH,US/Eastern,KMGY,36.0,89.0,29.65,6.0,SW,3.5,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2016,2016,2016,2,2,2
3,Source2,3,40.100590,-82.925194,0.01,Westerville,Franklin,OH,US/Eastern,KCMH,37.9,97.0,29.63,7.0,SSW,3.5,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2016,2016,2016,2,2,2
4,Source2,2,39.758274,-84.230507,0.00,Dayton,Montgomery,OH,US/Eastern,KDAY,34.0,100.0,29.66,7.0,WSW,3.5,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2016,2016,2016,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74914,Source2,3,32.731979,-117.111244,0.00,San Diego,San Diego,CA,US/Pacific,KSAN,72.0,46.0,30.01,10.0,NW,8.1,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2016,2016,2016,4,4,4
74915,Source2,3,33.913029,-118.125389,0.00,Downey,Los Angeles,CA,US/Pacific,KLGB,82.9,24.0,29.97,10.0,South,6.9,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2016,2016,2016,4,4,4
74916,Source2,2,34.121517,-117.536896,0.00,Rancho Cucamonga,San Bernardino,CA,US/Pacific,KONT,91.0,12.0,29.93,10.0,NW,6.9,Mostly Cloudy,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day,2016,2016,2016,4,4,4
74917,Source3,2,33.995079,-117.361183,0.00,Riverside,Riverside,CA,US/Pacific,KRAL,91.9,12.0,29.92,10.0,West,8.1,Mostly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2016,2016,2016,4,4,4
74918,Source2,2,34.034119,-118.013443,0.00,Whittier,Los Angeles,CA,US/Pacific,KEMT,89.6,16.0,29.98,10.0,South,5.8,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day,2016,2016,2016,4,4,4

#### Encoding

In [20]:
def onehot_encode(df, columns, prefixes):
    df = df.copy()
    for column, prefix in zip(columns, prefixes):
        dummies = pd.get_dummies(df[column], prefix=prefix)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(column, axis=1)
    return df

In [21]:
{column: len(df[column].unique()) for column in df.columns if df.dtypes[column] == 'str'}

{'Source': 2,
 'City': 758,
 'County': 70,
 'State': 3,
 'Timezone': 2,
 'Airport_Code': 118,
 'Wind_Direction': 23,
 'Weather_Condition': 41,
 'Sunrise_Sunset': 2,
 'Civil_Twilight': 2,
 'Nautical_Twilight': 2,
 'Astronomical_Twilight': 2}

In [22]:
df = onehot_encode(
    df,
    ['City', 'County', 'State', 'Airport_Code', 'Wind_Direction', 'Weather_Condition'],
    ['CI', 'CO', 'ST', 'AC', 'WD', 'WC']
)

In [23]:
df

,Source,Severity,Start_Lat,Start_Lng,Distance(mi),Timezone,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Start_Time_Year,End_Time_Year,Weather_Timestamp_Year,Start_Time_Month,End_Time_Month,Weather_Timestamp_Month,CI_Acampo,CI_Acton,CI_Agoura Hills,CI_Aguanga,CI_Akron,CI_Alameda,CI_Alamo,CI_Albany,CI_Albion,CI_Alhambra,CI_Aliso Viejo,CI_Alpine,CI_Alta,CI_Alviso,CI_Amelia,CI_American Canyon,CI_Anaheim,CI_Angels Camp,CI_Angelus Oaks,CI_Angwin,CI_Annapolis,CI_Antelope,CI_Antioch,CI_Anza,CI_Apple Valley,CI_Applegate,CI_Aptos,CI_Arbuckle,CI_Arcadia,CI_Arleta,CI_Aromas,CI_Artesia,CI_Atherton,CI_Atwater,CI_Auburn,CI_Azusa,CI_Baldwin Park,CI_Ballico,CI_Banning,CI_Barberton,CI_Batavia,CI_Bay Point,CI_Beaumont,CI_Beavercreek,CI_Bell Canyon,CI_Bell Gardens,CI_Bellflower,CI_Bellville,CI_Belmont,CI_Belvedere Tiburon,CI_Ben Lomond,CI_Benicia,CI_Berkeley,CI_Bermuda Dunes,CI_Berry Creek,CI_Bethel,CI_Beverly Hills,CI_Big Bear City,CI_Big Bear Lake,CI_Big Sur,CI_Biggs,CI_Birds Landing,CI_Blanchester,CI_Bloomingburg,CI_Bloomington,CI_Blue Jay,CI_Bodega,CI_Bodega Bay,CI_Bolinas,CI_Bonita,CI_Bonsall,CI_Borrego Springs,CI_Boulder Creek,CI_Bowling Green,CI_Brea,CI_Brecksville,CI_Brentwood,CI_Brisbane,CI_Brookpark,CI_Brooks,CI_Browns Valley,CI_Buena Park,CI_Burbank,CI_Burlingame,CI_Butte City,CI_Byron,CI_Cabazon,CI_Calabasas,CI_Calimesa,CI_Calistoga,CI_Camarillo,CI_Cambridge,CI_Cameron Park,CI_Camino,CI_Camp Pendleton,CI_Campbell,CI_Camptonville,CI_Canal Winchester,CI_Canoga Park,CI_Canyon Country,CI_Capay,CI_Capistrano Beach,CI_Capitola,CI_Cardiff By the Sea,CI_Carlsbad,CI_Carmel,CI_Carmel Valley,CI_Carmichael,CI_Carpinteria,CI_Carroll,CI_Carson,CI_Casstown,CI_Castaic,CI_Castro Valley,CI_Castroville,CI_Cathedral City,CI_Cazadero,CI_Cedar Glen,CI_Cedarpines Park,CI_Ceres,CI_Cerritos,CI_Challenge,CI_Chatsworth,CI_Cherry Valley,CI_Chino,CI_Chino Hills,CI_Chualar,CI_Chula Vista,CI_Circleville,CI_Citrus Heights,CI_City Of Industry,CI_Claremont,CI_Clarksburg,CI_Clayton,CI_Clearlake,CI_Clearlake Oaks,CI_Cleveland,CI_Cloverdale,CI_Cobb,CI_Colfax,CI_Colton,CI_Columbus,CI_Colusa,CI_Commerce,CI_Comptche,CI_Compton,CI_Concord,CI_Cool,CI_Copperopolis,CI_Corona,CI_Corona del Mar,CI_Coronado,CI_Corte Madera,CI_Costa Mesa,CI_Cotati,CI_Courtland,CI_Covina,CI_Coyote,CI_Crestline,CI_Crockett,CI_Crows Landing,CI_Culver City,CI_Cupertino,CI_Cypress,CI_Daly City,CI_Dana Point,CI_Danville,CI_Davenport,CI_Davis,CI_Dayton,CI_Del Mar,CI_Delaware,CI_Delhi,CI_Denair,CI_Desert Hot Springs,CI_Diablo,CI_Diamond Bar,CI_Diamond Springs,CI_Dillon Beach,CI_Discovery Bay,CI_Dixon,CI_Dobbins,CI_Dos Palos,CI_Downey,CI_Downieville,CI_Duarte,CI_Dublin,CI_Dulzura,CI_Dunnigan,CI_Dutch Flat,CI_East Palo Alto,CI_El Cajon,CI_El Cerrito,CI_El Dorado,CI_El Dorado Hills,CI_El Monte,CI_El Segundo,CI_El Sobrante,CI_Elk Grove,CI_Elverta,CI_Elyria,CI_Emerald Hills,CI_Emeryville,CI_Emigrant Gap,CI_Encinitas,CI_Encino,CI_Escalon,CI_Escondido,CI_Esparto,CI_Fair Oaks,CI_Fairborn,CI_Fairfield,CI_Fallbrook,CI_Farmington,CI_Felton,CI_Fiddletown,CI_Fillmore,CI_Findlay,CI_Firebaugh,CI_Folsom,CI_Fontana,CI_Foothill Ranch,CI_Forest Falls,CI_Foresthill,CI_Forestville,CI_Fort Bragg,CI_Foster City,CI_Fountain Valley,CI_Frankfort,CI_Fraziers Bottom,CI_Freedom,CI_Fremont,CI_French Camp,CI_Fullerton,CI_Fulton,CI_Galena,CI_Gallipolis,CI_Galloway,CI_Galt,CI_Garden Grove,CI_Garden Valley,CI_Gardena,CI_Georgetown,CI_Geyserville,CI_Gilroy,CI_Glen Ellen,CI_Glendale,CI_Glendora,CI_Glenn,CI_Gold River,CI_Goleta,CI_Gonzales,CI_Goshen,CI_Granada Hills,CI_Grand Terrace,CI_Granite Bay,CI_Grass Valley,CI_Graton,CI_Greenbrae,CI_Greenwood,CI_Gridley,CI_Grizzly Flats,CI_Grove City,CI_Groveport,CI_Gualala,CI_Guerneville,CI_Guinda,CI_Gustine,CI_Hacienda Heights,CI_Half Moon Bay,CI_Harbor City,CI_Hawaiian Gardens,CI_Hawthorne,CI_Hayward,CI_Healdsburg,CI_Hemet,CI_Herald,CI_Hercules,CI_Hesperia,CI_Hickman,CI_Hidden Hills,CI_Highland,CI_Hilliard,CI_Hillsborough,CI_Hilmar,CI_Hollister,CI_Homeland,CI_Hopland,CI_Hughson,CI_Huntington Beach,CI_Huntington Park,CI_Hurricane,CI_Idyllwild,CI_Imperial Beach,CI_Independence,CI_Indio,CI_Inglewood,CI_Ione,CI_Irvine,CI_Irwindale,CI_Isleton,CI_Jackson,CI_Jamestown,CI_Jamul,CI_Jenner,CI_Johnstown,CI_Joshua Tree,CI_Julian,CI_Kelseyville,CI_Kentfield,CI_Kenwood,CI_Keyes,CI_Knights Landing,CI_La Crescenta,CI_La Habra,CI_La Habra Heights,CI_La Honda,CI_La Jolla,CI_La Mesa,CI_La Mirada,CI_La Palma,CI_La Puente,CI_La Verne,CI_Ladera Ranch,CI_Lafayette,CI_Laguna Beach,CI_Laguna Hills,CI_Laguna Niguel,CI_Lake Arrowhead,CI_Lake Elsinore,CI_Lake Forest,CI_Lakeport,CI_Lakeside,CI_Lakewood,CI_Landers,CI_Larkspur,CI_Lathrop,CI_Lawndale,CI_Lebanon,CI_Lemon Grove,CI_Lima,CI_Lincoln,CI_Linden,CI_Little River,CI_Littlerock,CI_Livermore,CI_Livingston,CI_Llano,CI_Lockbourne,CI_Lockeford,CI_Lodi,CI_Loma Linda,CI_Lompoc,CI_London,CI_Long Beach,CI_Loomis,CI_Los Alamitos,CI_Los Altos,CI_Los Angeles,CI_Los Banos,CI_Los Gatos,CI_Lotus,CI_Lower Lake,CI_Lucerne,CI_Lucerne Valley,CI_Lynwood,CI_Lytle Creek,CI_Madison,CI_Maineville,CI_Malibu,CI_Mansfield,CI_Manteca,CI_Maple Heights,CI_March Air Reserve Base,CI_Marina,CI_Marina Del Rey,CI_Marina del Rey,CI_Martinez,CI_Marysville,CI_Mather,CI_Maxwell,CI_Maywood,CI_McClellan,CI_Mcclellan,CI_Meadow Vista,CI_Mendocino,CI_Mendota,CI_Menifee,CI_Menlo Park,CI_Mentone,CI_Merced,CI_Meridian,CI_Miamisburg,CI_Middletown,CI_Midway City,CI_Milford,CI_Mill Valley,CI_Millbrae,CI_Millersport,CI_Milpitas,CI_Mira Loma,CI_Mission Hills,CI_Mission Viejo,CI_Modesto,CI_Mokelumne Hill,CI_Monrovia,CI_Montara,CI_Montclair,CI_Monte Rio,CI_Monte Sereno,CI_Montebello,CI_Monterey,CI_Monterey Park,CI_Montrose,CI_Moorpark,CI_Moraine,CI_Moreno Valley,CI_Morgan Hill,CI_Morongo Valley,CI_Moscow,CI_Moss Beach,CI_Moss Landing,CI_Mount Hamilton,CI_Mount Sterling,CI_Mountain Center,CI_Mountain Ranch,CI_Mountain View,CI_Mt Baldy,CI_Muir Beach,CI_Murrieta,CI_Napa,CI_National City,CI_Nevada City,CI_New Carlisle,CI_New Richmond,CI_Newark,CI_Newbury Park,CI_Newcastle,CI_Newhall,CI_Newman,CI_Newport Beach,CI_Newport Coast,CI_Nicasio,CI_Nice,CI_Nicolaus,CI_Norco,CI_Norden,CI_North Baltimore,CI_North Highlands,CI_North Hills,CI_North Hollywood,CI_North Olmsted,CI_North Palm Springs,CI_North San Juan,CI_Northridge,CI_Norwalk,CI_Novato,CI_Nuevo,CI_Oak Hills,CI_Oak Park,CI_Oak View,CI_Oakdale,CI_Oakland,CI_Oakley,CI_Oberlin,CI_Occidental,CI_Oceanside,CI_Ojai,CI_Olivehurst,CI_Ontario,CI_Orange,CI_Orangevale,CI_Oregon House,CI_Oregonia,CI_Orient,CI_Orinda,CI_Oroville,CI_Owensville,CI_Oxnard,CI_Pacheco,CI_Pacific Palisades,CI_Pacifica,CI_Pacoima,CI_Paicines,CI_Pala,CI_Palermo,CI_Palm Desert,CI_Palm Springs,CI_Palmdale,CI_Palo Alto,CI_Palos Verdes Peninsula,CI_Panorama City,CI_Paramount,CI_Pataskala,CI_Patterson,CI_Pauma Valley,CI_Pearblossom,CI_Pebble Beach,CI_Peebles,CI_Penn Valley,CI_Penngrove,CI_Penryn,CI_Perris,CI_Pescadero,CI_Petaluma,CI_Phelan,CI_Pickerington,CI_Pico Rivera,CI_Pilot Hill,CI_Pine Grove,CI_Pinole,CI_Pinon Hills,CI_Pioneer,CI_Piqua,CI_Piru,CI_Pittsburg,CI_Placentia,CI_Placerville,CI_Playa Del Rey,CI_Pleasant Grove,CI_Pleasant Hill,CI_Pleasanton,CI_Plymouth,CI_Point Mugu Nawc,CI_Point Reyes Station,CI_Pollock Pines,CI_Pomona,CI_Pope Valley,CI_Port Costa,CI_Port Hueneme,CI_Porter Ranch,CI_Portola Valley,CI_Potter Valley,CI_Poway,CI_Princeton,CI_Ramona,CI_Ranchita,CI_Rancho Cordova,CI_Rancho Cucamonga,CI_Rancho Dominguez,CI_Rancho Mirage,CI_Rancho Murieta,CI_Rancho Santa Fe,CI_Rancho Santa Margarita,CI_Redlands,CI_Redondo Beach,CI_Redwood City,CI_Redwood Valley,CI_Rescue,CI_Reseda,CI_Reynoldsburg,CI_Rialto,CI_Richmond,CI_Rimforest,CI_Rio Linda,CI_Rio Vista,CI_Ripon,CI_Riverside,CI_Rocklin,CI_Rodeo,CI_Rohnert Park,CI_Rolling Hills Estates,CI_Rosemead,CI_Roseville,CI_Rough And Ready,CI_Rough and Ready,CI_Rowland Heights,CI_Royal Oaks,CI_Rumsey,CI_Running Springs,CI_Sabina,CI_Sacramento,CI_Saint Helena,CI_Salida,CI_Salinas,CI_San Andreas,CI_San Anselmo,CI_San Bernardino,CI_San Bruno,CI_San Carlos,CI_San Clemente,CI_San Diego,CI_San Dimas,CI_San Fernando,CI_San Francisco,CI_San Gabriel,CI_San Gregorio,CI_San Jacinto,CI_San Jose,CI_San Juan Bautista,CI_San Juan Capistrano,CI_San Leandro,CI_San Lorenzo,CI_San Marcos,CI_San Marino,CI_San Martin,CI_San Mateo,CI_San Pablo,CI_San Pedro,CI_San Quentin,CI_San Rafael,CI_San Ramon,CI_San Ysidro,CI_Santa Ana,CI_Santa Barbara,CI_Santa Clara,CI_Santa Clarita,CI_Santa Cruz,CI_Santa Fe Springs,CI_Santa Monica,CI_Santa Paula,CI_Santa Rosa,CI_Santa Rosa Valley,CI_Santa Ysabel,CI_Santee,CI_Saratoga,CI_Sardinia,CI_Sausalito,CI_Scotts Valley,CI_Seal Beach,CI_Seaside,CI_Sebastopol,CI_Seville,CI_Sheridan,CI_Sherman Oaks,CI_Shingle Springs,CI_Sierra City,CI_Signal Hill,CI_Silverado,CI_Simi Valley,CI_Skyforest,CI_Sloughhouse,CI_Smartsville,CI_Soda Springs,CI_Solana Beach,CI_Soledad,CI_Somerset,CI_Somis,CI_Sonoma,CI_Soquel,CI_South El Monte,CI_South Gate,CI_South Pasadena,CI_South San Francisco,CI_Spring Valley,CI_Springboro,CI_Springfield,CI_Stanford,CI_Stanton,CI_Stevenson Ranch,CI_Stevinson,CI_Stockton,CI_Strongsville,CI_Studio City,CI_Sugarloaf,CI_Suisun City,CI_Summerland,CI_Sun City,CI_Sun Valley,CI_Sunbury,CI_Sunland,CI_Sunnyvale,CI_Sunol,CI_Sunset Beach,CI_Sutter,CI_Sutter Creek,CI_Sylmar,CI_Tarzana,CI_Temecula,CI_Temple City,CI_The Sea Ranch,CI_Thousand Oaks,CI_Thousand Palms,CI_Tipp City,CI_Tiro,CI_Toluca Lake,CI_Tomales,CI_Topanga,CI_Torrance,CI_Trabuco Canyon,CI_Tracy,CI_Travis Afb,CI_Troy,CI_Tujunga,CI_Turlock,CI_Tustin,CI_Twin Peaks,CI_Ukiah,CI_Union City,CI_Universal City,CI_Upland,CI_Upper Lake,CI_Urbancrest,CI_Vacaville,CI_Valencia,CI_Vallejo,CI_Valley Center,CI_Valley Ford,CI_Valley Springs,CI_Valley Village,CI_Valyermo,CI_Van Nuys,CI_Vandalia,CI_Venice,CI_Ventura,CI_Vermilion,CI_Vernalis,CI_Vernon,CI_Victorville,CI_View Park,CI_Vista,CI_Volcano,CI_Walnut,CI_Walnut Creek,CI_Walnut Grove,CI_Warner Springs,CI_Waterford,CI_Watsonville,CI_Waynesville,CI_West Contra Costa,CI_West Covina,CI_West Hollywood,CI_West Point,CI_West Sacramento,CI_Westerville,CI_Westlake Village,CI_Westminster,CI_Wheatland,CI_Whitewater,CI_Whittier,CI_Wildomar,CI_Williams,CI_Williamsburg,CI_Willits,CI_Willows,CI_Wilmington,CI_Wilton,CI_Winchester,CI_Windsor,CI_Windsor Hills,CI_Winnetka,CI_Winters,CI_Winton,CI_Woodacre,CI_Woodbridge,CI_Woodland,CI_Woodland Hills,CI_Woodside,CI_Wrightwood,CI_Xenia,CI_Yorba Linda,CI_Yorkville,CI_Yountville,CI_Yuba City,CI_Yucaipa,CI_Yucca Valley,CI_Zamora,CI_Zanesville,CO_Adams,CO_Alameda,CO_Allen,CO_Amador,CO_Brown,CO_Butte,CO_Calaveras,CO_Clark,CO_Clermont,CO_Clinton,CO_Colusa,CO_Contra Costa,CO_Crawford,CO_Cuyahoga,CO_Delaware,CO_El Dorado,CO_Fairfield,CO_Fayette,CO_Franklin,CO_Fresno,CO_Gallia,CO_Glenn,CO_Greene,CO_Guernsey,CO_Hancock,CO_Lake,CO_Licking,CO_Lorain,CO_Los Angeles,CO_Madison,CO_Marin,CO_Medina,CO_Mendocino,CO_Merced,CO_Miami,CO_Monterey,CO_Montgomery,CO_Muskingum,CO_Napa,CO_Nevada,CO_Orange,CO_Pickaway,CO_Placer,CO_Putnam,CO_Richland,CO_Riverside,CO_Ross,CO_Sacramento,CO_San Benito,CO_San Bernardino,CO_San Diego,CO_San Francisco,CO_San Joaquin,CO_San Mateo,CO_Santa Barbara,CO_Santa Clara,CO_Santa Cruz,CO_Sierra,CO_Solano,CO_Sonoma,CO_Stanislaus,CO_Summit,CO_Sutter,CO_Tuolumne,CO_Ventura,CO_Warren,CO_Wayne,CO_Wood,CO_Yolo,CO_Yuba,ST_CA,ST_OH,ST_WV,AC_K3A6,AC_K3I2,AC_KAJO,AC_KAKR,AC_KAOH,AC_KAPC,AC_KAUN,AC_KBAB,AC_KBJJ,AC_KBKL,AC_KBLU,AC_KBUO,AC_KBUR,AC_KCCR,AC_KCIC,AC_KCLE,AC_KCMA,AC_KCMH,AC_KCNO,AC_KCQT,AC_KCRQ,AC_KCRW,AC_KCVH,AC_KDAY,AC_KDLZ,AC_KDVO,AC_KE16,AC_KEDU,AC_KEMT,AC_KF70,AC_KFDY,AC_KFFO,AC_KFUL,AC_KGOO,AC_KGXA,AC_KHAF,AC_KHAO,AC_KHHR,AC_KHWD,AC_KI69,AC_KILN,AC_KL35,AC_KLAX,AC_KLCK,AC_KLGB,AC_KLHM,AC_KLHQ,AC_KLPC,AC_KLPR,AC_KLVK,AC_KMAE,AC_KMCC,AC_KMCE,AC_KMER,AC_KMFD,AC_KMGY,AC_KMHR,AC_KMOD,AC_KMRY,AC_KMYF,AC_KMYV,AC_KNFG,AC_KNKX,AC_KNRS,AC_KNSI,AC_KNUQ,AC_KNXF,AC_KNXP,AC_KNZY,AC_KO22,AC_KO69,AC_KOAK,AC_KOKB,AC_KONT,AC_KOSU,AC_KOVE,AC_KOXR,AC_KPAO,AC_KPMD,AC_KPOC,AC_KPSP,AC_KPVF,AC_KRAL,AC_KRHV,AC_KRIV,AC_KRNM,AC_KSAC,AC_KSAN,AC_KSBA,AC_KSBD,AC_KSCK,AC_KSDM,AC_KSEE,AC_KSFO,AC_KSGH,AC_KSJC,AC_KSLI,AC_KSMF,AC_KSMO,AC_KSNA,AC_KSNS,AC_KSQL,AC_KSTS,AC_KSUU,AC_KTDZ,AC_KTOA,AC_KTRK,AC_KTRM,AC_KTZR,AC_KUKI,AC_KVCB,AC_KVCV,AC_KVES,AC_KVNY,AC_KVTA,AC_KWHP,AC_KWVI,AC_KZZV,WD_CALM,WD_E,WD_ENE,WD_ESE,WD_East,WD_N,WD_NE,WD_NNE,WD_NNW,WD_NW,WD_North,WD_S,WD_SE,WD_SSE,WD_SSW,WD_SW,WD_South,WD_VAR,WD_Variable,WD_W,WD_WNW,WD_WSW,WD_West,WC_Blowing Dust / Windy,WC_Blowing Sand,WC_Clear,WC_Cloudy,WC_Drizzle,WC_Fair,WC_Fair / Windy,WC_Fog,WC_Hail,WC_Haze,WC_Heavy Drizzle,WC_Heavy Rain,WC_Light Drizzle,WC_Light Freezing Drizzle,WC_Light Freezing Fog,WC_Light Freezing Rain,WC_Light Haze,WC_Light Rain,WC_Light Rain / Windy,WC_Light Rain Shower,WC_Light Rain Showers,WC_Light Rain with Thunder,WC_Light Snow,WC_Light Thunderstorms and Rain,WC_Mist,WC_Mostly Cloudy,WC_Mostly Cloudy / Windy,WC_Overcast,WC_Partly Cloudy,WC_Partly Cloudy / Windy,WC_Patches of Fog,WC_Rain,WC_Rain Showers,WC_Scattered Clouds,WC_Shallow Fog,WC_Showers in the Vicinity,WC_Smoke,WC_Snow,WC_Thunder in the Vicinity,WC_Thunderstorms and Rain,WC_Widespread Dust
0,Source2,2,39.063148,-84.032608,0.01,US/Eastern,36.0,100.0,29.67,10.0,3.5,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day,2016,2016,2016,2,2,2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [24]:
{column: len(df[column].unique()) for column in df.columns if df.dtypes[column] == 'str'}

{'Source': 2,
 'Timezone': 2,
 'Sunrise_Sunset': 2,
 'Civil_Twilight': 2,
 'Nautical_Twilight': 2,
 'Astronomical_Twilight': 2}

In [25]:
def get_binary_column(df, column):
    df = df.copy()
    if column == 'Source':
        return df[column].apply(lambda x: 1 if x == 'MapQuest' else 0)
    if column == 'Timezone':
        return df[column].apply(lambda x: 1 if x == 'US/Eastern' else 0)
    else:
        return df[column].apply(lambda x: 1 if x == 'Day' else 0)

In [26]:
df['Sunrise_Sunset'] = get_binary_column(df, 'Sunrise_Sunset')
df['Civil_Twilight'] = get_binary_column(df, 'Civil_Twilight')
df['Nautical_Twilight'] = get_binary_column(df, 'Nautical_Twilight')
df['Astronomical_Twilight'] = get_binary_column(df, 'Astronomical_Twilight')
df['Source'] = get_binary_column(df, 'Source')
df['Timezone'] = get_binary_column(df, 'Timezone')

In [27]:
df

,Source,Severity,Start_Lat,Start_Lng,Distance(mi),Timezone,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Start_Time_Year,End_Time_Year,Weather_Timestamp_Year,Start_Time_Month,End_Time_Month,Weather_Timestamp_Month,CI_Acampo,CI_Acton,CI_Agoura Hills,CI_Aguanga,CI_Akron,CI_Alameda,CI_Alamo,CI_Albany,CI_Albion,CI_Alhambra,CI_Aliso Viejo,CI_Alpine,CI_Alta,CI_Alviso,CI_Amelia,CI_American Canyon,CI_Anaheim,CI_Angels Camp,CI_Angelus Oaks,CI_Angwin,CI_Annapolis,CI_Antelope,CI_Antioch,CI_Anza,CI_Apple Valley,CI_Applegate,CI_Aptos,CI_Arbuckle,CI_Arcadia,CI_Arleta,CI_Aromas,CI_Artesia,CI_Atherton,CI_Atwater,CI_Auburn,CI_Azusa,CI_Baldwin Park,CI_Ballico,CI_Banning,CI_Barberton,CI_Batavia,CI_Bay Point,CI_Beaumont,CI_Beavercreek,CI_Bell Canyon,CI_Bell Gardens,CI_Bellflower,CI_Bellville,CI_Belmont,CI_Belvedere Tiburon,CI_Ben Lomond,CI_Benicia,CI_Berkeley,CI_Bermuda Dunes,CI_Berry Creek,CI_Bethel,CI_Beverly Hills,CI_Big Bear City,CI_Big Bear Lake,CI_Big Sur,CI_Biggs,CI_Birds Landing,CI_Blanchester,CI_Bloomingburg,CI_Bloomington,CI_Blue Jay,CI_Bodega,CI_Bodega Bay,CI_Bolinas,CI_Bonita,CI_Bonsall,CI_Borrego Springs,CI_Boulder Creek,CI_Bowling Green,CI_Brea,CI_Brecksville,CI_Brentwood,CI_Brisbane,CI_Brookpark,CI_Brooks,CI_Browns Valley,CI_Buena Park,CI_Burbank,CI_Burlingame,CI_Butte City,CI_Byron,CI_Cabazon,CI_Calabasas,CI_Calimesa,CI_Calistoga,CI_Camarillo,CI_Cambridge,CI_Cameron Park,CI_Camino,CI_Camp Pendleton,CI_Campbell,CI_Camptonville,CI_Canal Winchester,CI_Canoga Park,CI_Canyon Country,CI_Capay,CI_Capistrano Beach,CI_Capitola,CI_Cardiff By the Sea,CI_Carlsbad,CI_Carmel,CI_Carmel Valley,CI_Carmichael,CI_Carpinteria,CI_Carroll,CI_Carson,CI_Casstown,CI_Castaic,CI_Castro Valley,CI_Castroville,CI_Cathedral City,CI_Cazadero,CI_Cedar Glen,CI_Cedarpines Park,CI_Ceres,CI_Cerritos,CI_Challenge,CI_Chatsworth,CI_Cherry Valley,CI_Chino,CI_Chino Hills,CI_Chualar,CI_Chula Vista,CI_Circleville,CI_Citrus Heights,CI_City Of Industry,CI_Claremont,CI_Clarksburg,CI_Clayton,CI_Clearlake,CI_Clearlake Oaks,CI_Cleveland,CI_Cloverdale,CI_Cobb,CI_Colfax,CI_Colton,CI_Columbus,CI_Colusa,CI_Commerce,CI_Comptche,CI_Compton,CI_Concord,CI_Cool,CI_Copperopolis,CI_Corona,CI_Corona del Mar,CI_Coronado,CI_Corte Madera,CI_Costa Mesa,CI_Cotati,CI_Courtland,CI_Covina,CI_Coyote,CI_Crestline,CI_Crockett,CI_Crows Landing,CI_Culver City,CI_Cupertino,CI_Cypress,CI_Daly City,CI_Dana Point,CI_Danville,CI_Davenport,CI_Davis,CI_Dayton,CI_Del Mar,CI_Delaware,CI_Delhi,CI_Denair,CI_Desert Hot Springs,CI_Diablo,CI_Diamond Bar,CI_Diamond Springs,CI_Dillon Beach,CI_Discovery Bay,CI_Dixon,CI_Dobbins,CI_Dos Palos,CI_Downey,CI_Downieville,CI_Duarte,CI_Dublin,CI_Dulzura,CI_Dunnigan,CI_Dutch Flat,CI_East Palo Alto,CI_El Cajon,CI_El Cerrito,CI_El Dorado,CI_El Dorado Hills,CI_El Monte,CI_El Segundo,CI_El Sobrante,CI_Elk Grove,CI_Elverta,CI_Elyria,CI_Emerald Hills,CI_Emeryville,CI_Emigrant Gap,CI_Encinitas,CI_Encino,CI_Escalon,CI_Escondido,CI_Esparto,CI_Fair Oaks,CI_Fairborn,CI_Fairfield,CI_Fallbrook,CI_Farmington,CI_Felton,CI_Fiddletown,CI_Fillmore,CI_Findlay,CI_Firebaugh,CI_Folsom,CI_Fontana,CI_Foothill Ranch,CI_Forest Falls,CI_Foresthill,CI_Forestville,CI_Fort Bragg,CI_Foster City,CI_Fountain Valley,CI_Frankfort,CI_Fraziers Bottom,CI_Freedom,CI_Fremont,CI_French Camp,CI_Fullerton,CI_Fulton,CI_Galena,CI_Gallipolis,CI_Galloway,CI_Galt,CI_Garden Grove,CI_Garden Valley,CI_Gardena,CI_Georgetown,CI_Geyserville,CI_Gilroy,CI_Glen Ellen,CI_Glendale,CI_Glendora,CI_Glenn,CI_Gold River,CI_Goleta,CI_Gonzales,CI_Goshen,CI_Granada Hills,CI_Grand Terrace,CI_Granite Bay,CI_Grass Valley,CI_Graton,CI_Greenbrae,CI_Greenwood,CI_Gridley,CI_Grizzly Flats,CI_Grove City,CI_Groveport,CI_Gualala,CI_Guerneville,CI_Guinda,CI_Gustine,CI_Hacienda Heights,CI_Half Moon Bay,CI_Harbor City,CI_Hawaiian Gardens,CI_Hawthorne,CI_Hayward,CI_Healdsburg,CI_Hemet,CI_Herald,CI_Hercules,CI_Hesperia,CI_Hickman,CI_Hidden Hills,CI_Highland,CI_Hilliard,CI_Hillsborough,CI_Hilmar,CI_Hollister,CI_Homeland,CI_Hopland,CI_Hughson,CI_Huntington Beach,CI_Huntington Park,CI_Hurricane,CI_Idyllwild,CI_Imperial Beach,CI_Independence,CI_Indio,CI_Inglewood,CI_Ione,CI_Irvine,CI_Irwindale,CI_Isleton,CI_Jackson,CI_Jamestown,CI_Jamul,CI_Jenner,CI_Johnstown,CI_Joshua Tree,CI_Julian,CI_Kelseyville,CI_Kentfield,CI_Kenwood,CI_Keyes,CI_Knights Landing,CI_La Crescenta,CI_La Habra,CI_La Habra Heights,CI_La Honda,CI_La Jolla,CI_La Mesa,CI_La Mirada,CI_La Palma,CI_La Puente,CI_La Verne,CI_Ladera Ranch,CI_Lafayette,CI_Laguna Beach,CI_Laguna Hills,CI_Laguna Niguel,CI_Lake Arrowhead,CI_Lake Elsinore,CI_Lake Forest,CI_Lakeport,CI_Lakeside,CI_Lakewood,CI_Landers,CI_Larkspur,CI_Lathrop,CI_Lawndale,CI_Lebanon,CI_Lemon Grove,CI_Lima,CI_Lincoln,CI_Linden,CI_Little River,CI_Littlerock,CI_Livermore,CI_Livingston,CI_Llano,CI_Lockbourne,CI_Lockeford,CI_Lodi,CI_Loma Linda,CI_Lompoc,CI_London,CI_Long Beach,CI_Loomis,CI_Los Alamitos,CI_Los Altos,CI_Los Angeles,CI_Los Banos,CI_Los Gatos,CI_Lotus,CI_Lower Lake,CI_Lucerne,CI_Lucerne Valley,CI_Lynwood,CI_Lytle Creek,CI_Madison,CI_Maineville,CI_Malibu,CI_Mansfield,CI_Manteca,CI_Maple Heights,CI_March Air Reserve Base,CI_Marina,CI_Marina Del Rey,CI_Marina del Rey,CI_Martinez,CI_Marysville,CI_Mather,CI_Maxwell,CI_Maywood,CI_McClellan,CI_Mcclellan,CI_Meadow Vista,CI_Mendocino,CI_Mendota,CI_Menifee,CI_Menlo Park,CI_Mentone,CI_Merced,CI_Meridian,CI_Miamisburg,CI_Middletown,CI_Midway City,CI_Milford,CI_Mill Valley,CI_Millbrae,CI_Millersport,CI_Milpitas,CI_Mira Loma,CI_Mission Hills,CI_Mission Viejo,CI_Modesto,CI_Mokelumne Hill,CI_Monrovia,CI_Montara,CI_Montclair,CI_Monte Rio,CI_Monte Sereno,CI_Montebello,CI_Monterey,CI_Monterey Park,CI_Montrose,CI_Moorpark,CI_Moraine,CI_Moreno Valley,CI_Morgan Hill,CI_Morongo Valley,CI_Moscow,CI_Moss Beach,CI_Moss Landing,CI_Mount Hamilton,CI_Mount Sterling,CI_Mountain Center,CI_Mountain Ranch,CI_Mountain View,CI_Mt Baldy,CI_Muir Beach,CI_Murrieta,CI_Napa,CI_National City,CI_Nevada City,CI_New Carlisle,CI_New Richmond,CI_Newark,CI_Newbury Park,CI_Newcastle,CI_Newhall,CI_Newman,CI_Newport Beach,CI_Newport Coast,CI_Nicasio,CI_Nice,CI_Nicolaus,CI_Norco,CI_Norden,CI_North Baltimore,CI_North Highlands,CI_North Hills,CI_North Hollywood,CI_North Olmsted,CI_North Palm Springs,CI_North San Juan,CI_Northridge,CI_Norwalk,CI_Novato,CI_Nuevo,CI_Oak Hills,CI_Oak Park,CI_Oak View,CI_Oakdale,CI_Oakland,CI_Oakley,CI_Oberlin,CI_Occidental,CI_Oceanside,CI_Ojai,CI_Olivehurst,CI_Ontario,CI_Orange,CI_Orangevale,CI_Oregon House,CI_Oregonia,CI_Orient,CI_Orinda,CI_Oroville,CI_Owensville,CI_Oxnard,CI_Pacheco,CI_Pacific Palisades,CI_Pacifica,CI_Pacoima,CI_Paicines,CI_Pala,CI_Palermo,CI_Palm Desert,CI_Palm Springs,CI_Palmdale,CI_Palo Alto,CI_Palos Verdes Peninsula,CI_Panorama City,CI_Paramount,CI_Pataskala,CI_Patterson,CI_Pauma Valley,CI_Pearblossom,CI_Pebble Beach,CI_Peebles,CI_Penn Valley,CI_Penngrove,CI_Penryn,CI_Perris,CI_Pescadero,CI_Petaluma,CI_Phelan,CI_Pickerington,CI_Pico Rivera,CI_Pilot Hill,CI_Pine Grove,CI_Pinole,CI_Pinon Hills,CI_Pioneer,CI_Piqua,CI_Piru,CI_Pittsburg,CI_Placentia,CI_Placerville,CI_Playa Del Rey,CI_Pleasant Grove,CI_Pleasant Hill,CI_Pleasanton,CI_Plymouth,CI_Point Mugu Nawc,CI_Point Reyes Station,CI_Pollock Pines,CI_Pomona,CI_Pope Valley,CI_Port Costa,CI_Port Hueneme,CI_Porter Ranch,CI_Portola Valley,CI_Potter Valley,CI_Poway,CI_Princeton,CI_Ramona,CI_Ranchita,CI_Rancho Cordova,CI_Rancho Cucamonga,CI_Rancho Dominguez,CI_Rancho Mirage,CI_Rancho Murieta,CI_Rancho Santa Fe,CI_Rancho Santa Margarita,CI_Redlands,CI_Redondo Beach,CI_Redwood City,CI_Redwood Valley,CI_Rescue,CI_Reseda,CI_Reynoldsburg,CI_Rialto,CI_Richmond,CI_Rimforest,CI_Rio Linda,CI_Rio Vista,CI_Ripon,CI_Riverside,CI_Rocklin,CI_Rodeo,CI_Rohnert Park,CI_Rolling Hills Estates,CI_Rosemead,CI_Roseville,CI_Rough And Ready,CI_Rough and Ready,CI_Rowland Heights,CI_Royal Oaks,CI_Rumsey,CI_Running Springs,CI_Sabina,CI_Sacramento,CI_Saint Helena,CI_Salida,CI_Salinas,CI_San Andreas,CI_San Anselmo,CI_San Bernardino,CI_San Bruno,CI_San Carlos,CI_San Clemente,CI_San Diego,CI_San Dimas,CI_San Fernando,CI_San Francisco,CI_San Gabriel,CI_San Gregorio,CI_San Jacinto,CI_San Jose,CI_San Juan Bautista,CI_San Juan Capistrano,CI_San Leandro,CI_San Lorenzo,CI_San Marcos,CI_San Marino,CI_San Martin,CI_San Mateo,CI_San Pablo,CI_San Pedro,CI_San Quentin,CI_San Rafael,CI_San Ramon,CI_San Ysidro,CI_Santa Ana,CI_Santa Barbara,CI_Santa Clara,CI_Santa Clarita,CI_Santa Cruz,CI_Santa Fe Springs,CI_Santa Monica,CI_Santa Paula,CI_Santa Rosa,CI_Santa Rosa Valley,CI_Santa Ysabel,CI_Santee,CI_Saratoga,CI_Sardinia,CI_Sausalito,CI_Scotts Valley,CI_Seal Beach,CI_Seaside,CI_Sebastopol,CI_Seville,CI_Sheridan,CI_Sherman Oaks,CI_Shingle Springs,CI_Sierra City,CI_Signal Hill,CI_Silverado,CI_Simi Valley,CI_Skyforest,CI_Sloughhouse,CI_Smartsville,CI_Soda Springs,CI_Solana Beach,CI_Soledad,CI_Somerset,CI_Somis,CI_Sonoma,CI_Soquel,CI_South El Monte,CI_South Gate,CI_South Pasadena,CI_South San Francisco,CI_Spring Valley,CI_Springboro,CI_Springfield,CI_Stanford,CI_Stanton,CI_Stevenson Ranch,CI_Stevinson,CI_Stockton,CI_Strongsville,CI_Studio City,CI_Sugarloaf,CI_Suisun City,CI_Summerland,CI_Sun City,CI_Sun Valley,CI_Sunbury,CI_Sunland,CI_Sunnyvale,CI_Sunol,CI_Sunset Beach,CI_Sutter,CI_Sutter Creek,CI_Sylmar,CI_Tarzana,CI_Temecula,CI_Temple City,CI_The Sea Ranch,CI_Thousand Oaks,CI_Thousand Palms,CI_Tipp City,CI_Tiro,CI_Toluca Lake,CI_Tomales,CI_Topanga,CI_Torrance,CI_Trabuco Canyon,CI_Tracy,CI_Travis Afb,CI_Troy,CI_Tujunga,CI_Turlock,CI_Tustin,CI_Twin Peaks,CI_Ukiah,CI_Union City,CI_Universal City,CI_Upland,CI_Upper Lake,CI_Urbancrest,CI_Vacaville,CI_Valencia,CI_Vallejo,CI_Valley Center,CI_Valley Ford,CI_Valley Springs,CI_Valley Village,CI_Valyermo,CI_Van Nuys,CI_Vandalia,CI_Venice,CI_Ventura,CI_Vermilion,CI_Vernalis,CI_Vernon,CI_Victorville,CI_View Park,CI_Vista,CI_Volcano,CI_Walnut,CI_Walnut Creek,CI_Walnut Grove,CI_Warner Springs,CI_Waterford,CI_Watsonville,CI_Waynesville,CI_West Contra Costa,CI_West Covina,CI_West Hollywood,CI_West Point,CI_West Sacramento,CI_Westerville,CI_Westlake Village,CI_Westminster,CI_Wheatland,CI_Whitewater,CI_Whittier,CI_Wildomar,CI_Williams,CI_Williamsburg,CI_Willits,CI_Willows,CI_Wilmington,CI_Wilton,CI_Winchester,CI_Windsor,CI_Windsor Hills,CI_Winnetka,CI_Winters,CI_Winton,CI_Woodacre,CI_Woodbridge,CI_Woodland,CI_Woodland Hills,CI_Woodside,CI_Wrightwood,CI_Xenia,CI_Yorba Linda,CI_Yorkville,CI_Yountville,CI_Yuba City,CI_Yucaipa,CI_Yucca Valley,CI_Zamora,CI_Zanesville,CO_Adams,CO_Alameda,CO_Allen,CO_Amador,CO_Brown,CO_Butte,CO_Calaveras,CO_Clark,CO_Clermont,CO_Clinton,CO_Colusa,CO_Contra Costa,CO_Crawford,CO_Cuyahoga,CO_Delaware,CO_El Dorado,CO_Fairfield,CO_Fayette,CO_Franklin,CO_Fresno,CO_Gallia,CO_Glenn,CO_Greene,CO_Guernsey,CO_Hancock,CO_Lake,CO_Licking,CO_Lorain,CO_Los Angeles,CO_Madison,CO_Marin,CO_Medina,CO_Mendocino,CO_Merced,CO_Miami,CO_Monterey,CO_Montgomery,CO_Muskingum,CO_Napa,CO_Nevada,CO_Orange,CO_Pickaway,CO_Placer,CO_Putnam,CO_Richland,CO_Riverside,CO_Ross,CO_Sacramento,CO_San Benito,CO_San Bernardino,CO_San Diego,CO_San Francisco,CO_San Joaquin,CO_San Mateo,CO_Santa Barbara,CO_Santa Clara,CO_Santa Cruz,CO_Sierra,CO_Solano,CO_Sonoma,CO_Stanislaus,CO_Summit,CO_Sutter,CO_Tuolumne,CO_Ventura,CO_Warren,CO_Wayne,CO_Wood,CO_Yolo,CO_Yuba,ST_CA,ST_OH,ST_WV,AC_K3A6,AC_K3I2,AC_KAJO,AC_KAKR,AC_KAOH,AC_KAPC,AC_KAUN,AC_KBAB,AC_KBJJ,AC_KBKL,AC_KBLU,AC_KBUO,AC_KBUR,AC_KCCR,AC_KCIC,AC_KCLE,AC_KCMA,AC_KCMH,AC_KCNO,AC_KCQT,AC_KCRQ,AC_KCRW,AC_KCVH,AC_KDAY,AC_KDLZ,AC_KDVO,AC_KE16,AC_KEDU,AC_KEMT,AC_KF70,AC_KFDY,AC_KFFO,AC_KFUL,AC_KGOO,AC_KGXA,AC_KHAF,AC_KHAO,AC_KHHR,AC_KHWD,AC_KI69,AC_KILN,AC_KL35,AC_KLAX,AC_KLCK,AC_KLGB,AC_KLHM,AC_KLHQ,AC_KLPC,AC_KLPR,AC_KLVK,AC_KMAE,AC_KMCC,AC_KMCE,AC_KMER,AC_KMFD,AC_KMGY,AC_KMHR,AC_KMOD,AC_KMRY,AC_KMYF,AC_KMYV,AC_KNFG,AC_KNKX,AC_KNRS,AC_KNSI,AC_KNUQ,AC_KNXF,AC_KNXP,AC_KNZY,AC_KO22,AC_KO69,AC_KOAK,AC_KOKB,AC_KONT,AC_KOSU,AC_KOVE,AC_KOXR,AC_KPAO,AC_KPMD,AC_KPOC,AC_KPSP,AC_KPVF,AC_KRAL,AC_KRHV,AC_KRIV,AC_KRNM,AC_KSAC,AC_KSAN,AC_KSBA,AC_KSBD,AC_KSCK,AC_KSDM,AC_KSEE,AC_KSFO,AC_KSGH,AC_KSJC,AC_KSLI,AC_KSMF,AC_KSMO,AC_KSNA,AC_KSNS,AC_KSQL,AC_KSTS,AC_KSUU,AC_KTDZ,AC_KTOA,AC_KTRK,AC_KTRM,AC_KTZR,AC_KUKI,AC_KVCB,AC_KVCV,AC_KVES,AC_KVNY,AC_KVTA,AC_KWHP,AC_KWVI,AC_KZZV,WD_CALM,WD_E,WD_ENE,WD_ESE,WD_East,WD_N,WD_NE,WD_NNE,WD_NNW,WD_NW,WD_North,WD_S,WD_SE,WD_SSE,WD_SSW,WD_SW,WD_South,WD_VAR,WD_Variable,WD_W,WD_WNW,WD_WSW,WD_West,WC_Blowing Dust / Windy,WC_Blowing Sand,WC_Clear,WC_Cloudy,WC_Drizzle,WC_Fair,WC_Fair / Windy,WC_Fog,WC_Hail,WC_Haze,WC_Heavy Drizzle,WC_Heavy Rain,WC_Light Drizzle,WC_Light Freezing Drizzle,WC_Light Freezing Fog,WC_Light Freezing Rain,WC_Light Haze,WC_Light Rain,WC_Light Rain / Windy,WC_Light Rain Shower,WC_Light Rain Showers,WC_Light Rain with Thunder,WC_Light Snow,WC_Light Thunderstorms and Rain,WC_Mist,WC_Mostly Cloudy,WC_Mostly Cloudy / Windy,WC_Overcast,WC_Partly Cloudy,WC_Partly Cloudy / Windy,WC_Patches of Fog,WC_Rain,WC_Rain Showers,WC_Scattered Clouds,WC_Shallow Fog,WC_Showers in the Vicinity,WC_Smoke,WC_Snow,WC_Thunder in the Vicinity,WC_Thunderstorms and Rain,WC_Widespread Dust
0,0,2,39.063148,-84.032608,0.01,1,36.0,100.0,29.67,10.0,3.5,False,False,False,False,False,False,False,False,False,False,False,True,False,0,0,1,1,2016,2016,2016,2,2,2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

#### Splitting and Scaling

In [28]:
y = df['Severity'].copy()
X = df.drop('Severity', axis=1).copy()

In [29]:
y.unique()

array([2, 3, 1, 4])

In [30]:
y = y -1

In [31]:
y.unique()

array([1, 2, 0, 3])

In [33]:
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=1)

### Training

In [35]:
X.shape

(74919, 1046)

In [36]:
inputs = tf.keras.Input(shape=(X.shape[1], ))
x = tf.keras.layers.Dense(64, activation='relu')(inputs)
x = tf.keras.layers.Dense(64, activation='relu')(x)
outputs = tf.keras.layers.Dense(4, activation='softmax')(x)

model = tf.keras.Model(inputs, outputs)

In [38]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

batch_size = 32
epochs = 20

history = model.fit(
    X_train,
    y_train,
    validation_split = 0.2,
    batch_size=batch_size,
    epochs=epochs,
    callbacks=[
        tf.keras.callbacks.ReduceLROnPlateau(),
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True
        )
    ]
)

Epoch 1/20
1312/1312 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7827 - loss: 0.4665 - val_accuracy: 0.8062 - val_loss: 0.4236 - learning_rate: 0.0010
Epoch 2/20
1312/1312 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8103 - loss: 0.4079 - val_accuracy: 0.8113 - val_loss: 0.4084 - learning_rate: 0.0010
Epoch 3/20
1312/1312 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8147 - loss: 0.3934 - val_accuracy: 0.8109 - val_loss: 0.4025 - learning_rate: 0.0010
Epoch 4/20
1312/1312 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8186 - loss: 0.3857 - val_accuracy: 0.8170 - val_loss: 0.4052 - learning_rate: 0.0010
Epoch 5/20
1312/1312 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.8238 - loss: 0.3792 - val_accuracy: 0.8154 - val_loss: 0.4053 - learning_rate: 0.0010
Epoch 6/20
1312/1312 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8253 - loss: 0.3716 - val_accuracy: 0.8171 - val_loss: 0.4089 - learning_rate: 0.0010

### Results

In [39]:
print("Test Accuracy:", model.evaluate(X_test, y_test)[1])

703/703 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8108 - loss: 0.4111
Test Accuracy: 0.8107759356498718